package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Отсортировать матчи")
    void generatedTest() {
        step("Зайти на страницу https://1xstavka.ru/line/Football/", () -> {
            step("// todo: just add selenium action");
        });

        step("Собрать коллекцию матчей(чемпионат, название матча, дата, время) из главной таблицы", () -> {
            step("// todo: just add selenium action");
        });

        step("Вывести количество матчей по каждому из чемпионатов", () -> {
            step("// todo: just add selenium action");
        });

        step("Отсортировать матчи по дате и времени(независимо от чемпионата) и вывести эти данные в консоль", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://1xstavka.ru/line/Football/'", () ->
            open("https://1xstavka.ru/line/Football/"));

        step("Page title should have text 'Access to website is restricted'", () -> {
            String expectedTitle = "Access to website is restricted";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://1xstavka.ru/line/Football/'", () ->
            open("https://1xstavka.ru/line/Football/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}